AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
  - AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
  CodeDeployRole:
    Type: String
    Description: IAM role to allow AWS CodeDeploy to manage deployment of AWS Lambda functions
  Stage:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: ""

Globals:
  Function:
    AutoPublishAlias: live
    DeploymentPreference:
      Enabled: true
      Type: AllAtOnce
      Role: !Ref CodeDeployRole
      Timeout: 30

Resources:
  ESSendSMSNotification:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/ESSendSMSNotification
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /sms
            Method: post
  ConfigLambdaPermissionSMSNotification:
    Type: AWS::Lambda::Permission
    DependsOn:
      - ESSendSMSNotification
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ESSendSMSNotification
      Principal: apigateway.amazonaws.com
  
  ESSendEmergencyVoiceCall:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/ESSendEmergencyVoiceCall
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /voice
            Method: post
  ConfigLambdaPermissionVoice:
    Type: AWS::Lambda::Permission
    DependsOn:
      - ESSendEmergencyVoiceCall
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ESSendEmergencyVoiceCall
      Principal: apigateway.amazonaws.com

  ESPollLocation:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/ESPollLocation
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /poll
            Method: post
  ConfigLambdaPermissionPoll:
    Type: AWS::Lambda::Permission
    DependsOn:
      - ESPollLocation
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ESPollLocation
      Principal: apigateway.amazonaws.com

  LambdaExecutionRole:
    Description: Creating service role in IAM for AWS Lambda
    Type: AWS::IAM::Role
    Properties:
      RoleName: "CodeStar-emergenseek-bac-Execution-Lambda"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
       - arn:aws:iam::aws:policy/AdministratorAccess
      PermissionsBoundary: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/CodeStar_${ProjectId}_PermissionsBoundary"