AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ESPollLoop
  
  SAM template for locally testing ESPollLoop

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  ESPollLoop:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: main.zip
      Handler: main
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          # Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          # Properties:
          #   Path: /loop
          #   Method: POST
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Input: "{\"tier\": 1}"

Outputs:
  ESPollLoopAPI:
    Description: "API Gateway endpoint URL for Dev environment for ESPollLoop function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/"

  ESPollLoopFunction:
    Description: "ESPollLoop function ARN"
    Value: !GetAtt ESPollLoopFunction.Arn

  ESPollLoopFunctionIamRole:
    Description: "Implicit IAM Role created for ESPollLoop function"
    Value: !GetAtt ESPollLoopRole.Arn