AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ESAddContact
  
  SAM template for locally testing ESAddContact

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  ESAddContactFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: main.zip
      Handler: main
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /contact/{user_id+}
            Method: POST

Outputs:
  ESAddContactAPI:
    Description: "API Gateway endpoint URL for Dev environment for ESAddContact function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/"

  ESAddContactFunction:
    Description: "ESAddContact function ARN"
    Value: !GetAtt ESAddContactFunction.Arn

  ESAddContactFunctionIamRole:
    Description: "Implicit IAM Role created for ESAddContact function"
    Value: !GetAtt ESAddContactRole.Arn