AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ESManageSettings
  
  SAM template for locally testing ESManageSettings

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  ESManageSettingsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: main.zip
      Handler: main
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /settings/{user_id+}
            Method: ANY

Outputs:
  ESManageSettingsAPI:
    Description: "API Gateway endpoint URL for Dev environment for ESManageSettings function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/"

  ESManageSettingsFunction:
    Description: "ESManageSettings function ARN"
    Value: !GetAtt ESManageSettingsFunction.Arn

  ESManageSettingsFunctionIamRole:
    Description: "Implicit IAM Role created for ESManageSettings function"
    Value: !GetAtt ESManageSettingsRole.Arn