AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ESManageProfile
  
  SAM template for locally testing ESManageProfile

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  ESManageProfileFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: main.zip
      Handler: main
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /profile/{user_id+}
            Method: ANY

Outputs:
  ESManageProfileAPI:
    Description: "API Gateway endpoint URL for Dev environment for ESManageProfile function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/"

  ESManageProfileFunction:
    Description: "ESManageProfile function ARN"
    Value: !GetAtt ESManageProfileFunction.Arn

  ESManageProfileFunctionIamRole:
    Description: "Implicit IAM Role created for ESManageProfile function"
    Value: !GetAtt ESManageProfileRole.Arn